// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1izvlImT64vRYhEWM25H1lnkInATsFYI',
    appId: '1:55101647288:web:118de2c0cb8fe39035874d',
    messagingSenderId: '55101647288',
    projectId: 'callone-583e5',
    authDomain: 'callone-583e5.firebaseapp.com',
    storageBucket: 'callone-583e5.firebasestorage.app',
    measurementId: 'G-3YDE4QYJW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfWT5mJUCZKeuglYeiK0zw3ffi_eDnpo0',
    appId: '1:55101647288:android:9522a3cf257abd5935874d',
    messagingSenderId: '55101647288',
    projectId: 'callone-583e5',
    storageBucket: 'callone-583e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYDANNMATsEqsLaLnO52ZiCzojoSZavo',
    appId: '1:55101647288:ios:7f72412ee8c6334935874d',
    messagingSenderId: '55101647288',
    projectId: 'callone-583e5',
    storageBucket: 'callone-583e5.firebasestorage.app',
    iosBundleId: 'com.example.onecallDoctor',
  );
}
